spring.application.name=portfolio-backend

spring.datasource.url=jdbc:postgresql://dpg-d6jgmebuibrs73alq7i0-a:5432/auto_jnl3
spring.datasource.username=auto
spring.datasource.password=UOsUZMGUgkGpQ0EVxdfDO1mjTuMEPtX0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html